.gitignore
.travis.yml
LICENSE.txt
MANIFEST.in
README.rst
rasterfoundry/api.py
rasterfoundry/exceptions.py
rasterfoundry/models/__init__.py
rasterfoundry/models/project.py
rasterfoundry/spec.yml
setup.cfg
setup.py
tests/test_sample.py
tox.ini

Split the Raster Foundry Python client out from the main repository and do any work necessary to support cutting a release:
- Rename to `rasterfoundry`
- Add more layers of release testing to `tox`
- Add Travis CI support
- Add license
- Update README
Fixes https://github.com/azavea/raster-foundry/issues/1598.
---
**Testing**
Inspect the diff and ensure the Travis build succeeds.

Port Python client from main repository

---

MANIFEST.in
examples/Projects.ipynb
rasterfoundry/__init__.py
rasterfoundry/decorators.py
rasterfoundry/models/project.py
requirements.txt
scripts/update
setup.cfg
setup.py
tests/test_notebook_check.py

Overview
------
This PR adds `get_map`, `add_to`, and `compare` methods to projects, and an example notebook showing how to use them.
Testing
------
- `./scripts/update`
- `source venv/bin/activate`
- `jupyter notebook`
- open `examples/Projects.ipynb` from the notebook home
- fill in your `refresh_token`, and specify `host='app.staging.rasterfoundry.com'` for `api=...`
- run the notebook, changing projects as appropriate to get projects that you actually have
- there are [tests for this](https://github.com/azavea/raster-foundry-python-client/blob/54c9e0f9b7faab89ff051043769e3b07bc69ebf2/tests/test_notebook_check.py) in the commit. Verify that they make sense.
Closes azavea/raster-foundry#1632
Closes #3

Add leaflet support to project model

---

examples/Projects.ipynb
rasterfoundry/api.py
rasterfoundry/models/__init__.py
rasterfoundry/models/map_token.py
rasterfoundry/models/project.py
rasterfoundry/spec.yml
scripts/update
setup.py

Overview
------
This PR adds convenience methods to `Project`s for fetching map tokens and for downloading PNGs and geotiffs.
Notes
------
There are changes to the swagger spec that need to be propagated back to the main repository. I'll put up another PR for those changes momentarily.
Testing
------
- `./scripts/update`
- `source venv/bin/activate(.fish)`
- `pip install numpy matplotlib rasterio==1.0a8` (since these aren't project dependencies, but you'll need them to run one of the cells in the notebook)
- `jupyter notebook`
- open `examples/Projects.ipynb`
- set `host=app.staging.rasterfoundry.com` in `api=...`
- run the first two cells, then skip down to the export section
- pick a project you've shared previously with ingested scenes
- Run the cells in the export section
Closes …

Add convenience methods to projects

---

scripts/update
setup.py

Overview
------
This PR makes it so that `./scripts/update` works the same on Mac as it does on Linux.
For some reason, `setup.py develop` fails to install `cryptography`, while `pip install -e .`,
which _runs `setup.py develop` as its last step_, succeeds.
Also it relaxed the notebook dependency, since apparently `ipyleaflet` installs 5.0.0 right
now, and paying the cost to install `notebook` twice is a draaaaaag.
Testing
------
- be on a Mac
- run `./scripts/update`
- observe success
Fixes #5

Fix install for Mac OS

---

rasterfoundry/api.py
rasterfoundry/models/project.py

@rossbernet, @tgilcrest, and @jmorrison1847 are starting to use the client for demo prep. This enables them to create non-public projects for demo purposes while still being able to show the projects in the notebook.
Trivial, merging.

Include token with api request

---

rasterfoundry/spec.yml

Overview
------
This PR pulls over the current swagger spec from the main Raster Foundry repository and updates it it includes post body parameters for `/scenes/` and so bravado doesn't choke on the `discriminator` present in `SceneQueryParameters`.
Testing
------
- `./scripts/update`
- `source venv/bin/activate[.fish]`
- `ipython`, then run:
```python
import uuid
api = API(<your refresh token>, host=...)
api.client.Imagery.post_scenes(**{'scene': {'organizationId': str(uuid.uuid4())}})
```
The client should complain about normal things like that request being destined for failure, rather than about receiving any parameters at all.

Add scenes post body parameters

---

rasterfoundry/models/tests/test_upload.py
rasterfoundry/models/upload.py
setup.py

Overview
------
This PR introduces a model to handle posting uploads to the API.
Notes
------
I discovered while putting this together that our swagger spec includes some aspirational 201 return codes. I fixed those in 
Testing
------
- find a file you like and put it somewhere
- initialize this API client (probably point to staging)
- create an upload from local files, using the tests as an example of how to do that (but without `dry_run=True`)
Closes #6

Support local file uploads from client

---

rasterfoundry/api.py

Overview
------
Without relative imports, the installed package was looking for a globally available module called `models` to import, which it couldn't find. Relative import lets it know to use the `models` module in itself.
Testing
------
- create a python 3 virtualenv: `python3 -m venv venv`
- activate it
- `pip install -e .`
- open a python3 shell
- try to import the API:
```python
```
- if that doesn't fail, you win
- do the same for python 2, starting with `virtualenv venv` instead of `python3 -m venv venv`

Make imports in api.py relative

---

.travis.yml
rasterfoundry/spec.yml

Overview
------
Travis CI skipped our deploy due to the migration from `azavea/raster-foundry` to `raster-foundry/raster-foundry`. This fixes that in `.travis.yml` and updates references in the spec.
Tests
------
Not testable

Correct repo references

---

setup.py

Bump `cryptography` version to `2.x` to take advantage of the new `manylinux1 wheel` [installation method](https://cryptography.io/en/latest/installation/#building-cryptography-on-linux). This will enable us to install the module without installing any additional development packages.
Although tests were passing in CI, Travis CI build machines include `python-dev` so my changes weren't actually being tested.  As a workaround, I included a `Dockerfile` based off of Ubuntu Trusty so that I could test installation on a clean Ubuntu setup. It will be removed before this PR is merged.
- Build the Docker container, make sure that the `pip`  installation completes successfully. Then, attempt to use the API.
```bash
$ docker build -t rf-python .
$ docker run -it rf-python python 
Python 2.7.6 …
```

Bump cryptography version to 2.x

---

rasterfoundry/decorators.py
tests/test_notebook_check.py

Overview
------
When the function that fails the notebook check takes arguments, those arguments get passed to whatever the `@check_notebook` decorator returns. Since `no_op` takes no arguments, this causes a `TypeError` in real life that wasn't exercised by the test. This PR fixes the `no_op` function the decorator returns and adds a test that exercises this case.
Testing
------
- verify that the [new test](https://github.com/raster-foundry/raster-foundry-python-client/blob/a7d63b1d686aa72cb263649981ef4a5a012854d3/tests/test_notebook_check.py#L12-L20) exercises this problem
Closes nothing

Add *args and **kwargs to no_op function in notebook support check

---

rasterfoundry/exceptions.py
rasterfoundry/models/project.py
tox.ini

A few tweaks to make the client more ergonomic:
- Clarifies the bounding box format which is required.
- Raises exceptions with a helpful suggestion when export requests time out, and raises an exception when they error otherwise.
- `source venv/bin/activate`
- `jupyter notebook`
- Use the `Projects.ipynb` example or your own to get to the point where you have a `Project` object that you can call `geotiff()` on.
- Confirm that calling `.geotiff()` and `.png()` on the project object works generally.
- Confirm that setting the `zoom` parameter really high when calling the previous two functions results in a `GatewayTimeoutException` with a helpful message being raised.
- Confirm that passing in garbage for the `bbox` parameter causes an exception to be raised.

Minor usability fixes

---

README.rst
rasterfoundry/models/project.py

This PR adds a method to the `Project` class that starts a raster-vision predict job on AWS Batch.  This job will download the image files associated with the project, and then run object detection on them. To test this PR, you can run the following snippet which will start a job in the R&D account, and will place the predictions for the Oakland project in `s3://raster-vision/results/detection/predict/lhf_test/predictions.json`. You can then view the output along with the original TIFF file in QGIS. To get the URI for the TIFF file, you can run `proj.get_image_source_uris()`.
```
token = ''
api = API(refresh_token=token)
proj = api.projects[0]
proj.start_predict_job(
's3://raster-vision/results/detection/train/lhf_ships_neg0/train/inference_graph.pb', …
```

Start raster-vision predict job

---

rasterfoundry/api.py
rasterfoundry/models/project.py
rasterfoundry/settings.py
rasterfoundry/utils.py
setup.py

This PR adds a method to start raster-vision jobs that run the `prep_train_data` script. This allows one to easily generate training data zip files given projects ids and annotation URIs. This is related to https://github.com/azavea/raster-vision/pull/142. 
```
token = ...
api = API(refresh_token=token)
project_ids = [
'357ddf1f-2e5e-4420-8e75-0eed12d2d20f',
'4f073c7e-978e-483e-9848-17010cbad468',
'72d1eadb-2e4b-4e07-81d6-cc78a1ff29a1',
'7030c078-cf3e-403f-934a-cef039e56b2d',
'f38d0ea0-1b11-4256-9ca6-5464ca30bbaf'
]
annotation_uris = [
's3://raster-vision/datasets/detection/jm_ships/2017-09-18-singapore-final.geojson',
's3://raster-vision/datasets/detection/jm_ships/2017-08-20-hong-kong-final.geojson', …
```

Add method to start prep_train_data job

---

rasterfoundry/models/__init__.py
rasterfoundry/models/project.py
rasterfoundry/models/upload.py
rasterfoundry/spec.yml

This adds initial support for creating uploads of planet imagery directly from the API.
To Test, obtain a planet API key and get a refresh token for Raster Foundry:
```import os
from rasterfoundry.models import Project, Upload
org_id = 'dfac6307-b5ef-43f7-beda-b9f208bb7726'
datasource = '3d5b6e55-c9b7-4c86-b913-f45ae39296f7'
refresh_token = '<>'
planet_key = '<>'
api = API(refresh_token=refresh_token)
planet_ids = ['PSScene4Band:20170929_180204_0f35']
upload_create = Upload.upload_create_from_planet(
datasource, org_id, planet_ids, project_id=project.id,
metadata={'planetKey': planet_key}
)
upload = Upload.create(api, upload_create)
```
Verify that upload starts processing

Add Planet Upload Support

---

rasterfoundry/models/project.py
rasterfoundry/spec.yml

This PR exposes the `colorCorrect` query parameter of the tileserver's export endpoint. A user can now opt-in to removing color-corrections by providing the `raw` (boolean) argument to `Project.get_export`, `Project.png` and `Project.geotiff`. `raw` defaults to false so no existing behavior is changed.
There seems to be an issue on the tile-server side which is causing this to not actually work.

Add option to allow for raw (non-color-corrected) exports

---

examples/Analyses.ipynb
rasterfoundry/api.py
rasterfoundry/models/__init__.py
rasterfoundry/models/analysis.py
rasterfoundry/spec.yml

Add analyses to api object
Create Analysis model class
Does not support editing or creation via the client yet - we need to figure out universal MAML support first
* Run through the new example Analysis notebook and verify that it works as expected
* Try exporting a raw single band tif of the export. I haven't been able to get to this step yet, since the client assumes that the host you give it is of form "api.x.y" to create a tile server host of "tiles.x.y"
Depends on https://github.com/raster-foundry/raster-foundry/pull/2867 to verify that the export part works
Closes #39

Support analysis preview and raw export

---

rasterfoundry/api.py
rasterfoundry/aws/s3.py
rasterfoundry/models/project.py
rasterfoundry/settings.py
rasterfoundry/spec.yml
rasterfoundry/utils.py

This PR adds a method to posts annotations for a project that are stored in a JSON file on S3. This will be called by the Lambda function in https://github.com/azavea/raster-foundry-deployment/pull/115. This also makes some other changes to stay in sync with the latest RV and removes some methods which are not useful and annoying to maintain.
To test making a prediction, run the following commands:
```
token = 'XXX'
api = API(refresh_token=token)
from rasterfoundry.utils import RasterVisionBatchClient
rv_batch_client = RasterVisionBatchClient(
branch_name='lf/rfint', job_queue='raster-vision-cpu',
job_definition='raster-vision-cpu')
from rasterfoundry.models.project import Project
uuid = 'de3780a1-9f3e-4fa3-a811-ad3060b64866'
proj = …
```

Add method to post annotations for project

---

README.rst
rasterfoundry/api.py

Overview
-----
This PR makes it so users can point to a specific swagger spec if they need to, otherwise it just points
to `master` on the raster-foundry/raster-foundry-api-spec repo. Once we have a release of that, it
can point to a specific release.
Testing
-----
- add a print to either the `load_url` or `load_file` branch of the api client initialization
- start an ipython session with no special environment variables
- create a client
- verify that your print either did or didn't happen
- call `.projects` on the client you created and verify it works
- start an ipython session with `RF_API_SPEC_PATH` set to `rasterfoundry/spec.yml`
- create a client
- verify that your print either did or didn't happen
- call `.projects` on the client you created and verify it works
Closes #48

Point to user-configable swagger spec location

---

.gitignore
examples/Analyses.ipynb
examples/Export.ipynb
examples/Projects.ipynb
examples/Uploads.ipynb
rasterfoundry/api.py
rasterfoundry/models/__init__.py
rasterfoundry/models/analysis.py
rasterfoundry/models/export.py
rasterfoundry/models/project.py
rasterfoundry/spec.yml
setup.py

Overview
-----
This PR adds support for asynchronous exports to analyses and projects. It includes:
- an `Export` model to provide sugar around the bravado auto-generated API client
- new or updated example notebooks for analyses and projects to show asynchronous exports
- an example notebook for exports to show users everything they can do with `Export` objects
- a change from `get_export` to `get_thumbnail` for synchronous exports
- a `create_export` method for projects and analyses
Testing
-----
- run through the `Export`, `Project`, and `Analysis` example notebooks with an api pointed at
staging
Supersedes #47 
Closes #47 
Closes #46 
Closes #45

Support async exports

---

rasterfoundry/api.py

Overview
-----
This PR points to a specific release of the API spec by default, instead of whatever happens to be on
`master`.
It also removes the locally stored spec to avoid confusing people (and for fun!).
Testing
-----
- ci
- initialize a client --
```python
>>> from rasterfoundry.api import API
>>> client = API(api_token='your api token here')
>>> #or
>>> client = API('your refresh token here')
```
- if it succeeds, you're good
Closes #57

Point to permanent location by default for spec

---

examples/Datasources.ipynb
rasterfoundry/api.py
rasterfoundry/models/__init__.py
rasterfoundry/models/analysis.py
rasterfoundry/models/datasource.py
rasterfoundry/models/export.py
rasterfoundry/models/project.py

This PR:
- adds some convenience functions for datasources' CRUD
- adds an example notebook for it
How to test:
- Point to spec in here `https://raw.githubusercontent.com/raster-foundry/raster-foundry-api-spec/feature/asu/update-first-class-object-crud-spec/spec/spec.yml`
- Run the example notebook
This is the first part of https://github.com/raster-foundry/raster-foundry-python-client/issues/53

Add convenience functions and example notebook for datasource CRUD

---

CHANGELOG.rst
rasterfoundry/api.py

This PR updates client initialization to use the new auth payload name from the spec. Having a parameter
named `refreshToken` that expects to have a key `refresh_token` was confusing, but no longer must we toil under the weight of our past deceptions.
* Initialize a client
* it should work

Use new name for tokens endpoint post
